from __future__ import annotations

import argparse
import importlib
import sys

COMMAND_MODULES = {
    "identity-baseline": "identity_baseline",
    "visual-residual": "visual_residual_baseline",
    "scaled-visual": "scaled_visual_residual_baseline",
    "top-safe-visual": "top_safe_scaled_visual_residual_baseline",
    "two-head-visual": "two_head_visual_residual_baseline",
    "top-pair-head": "top_pair_head_2d_visual_residual_baseline",
    "identity-gate": "identity_anchored_gate_baseline",
    "final-a-production": "step16_production_a",
    "final-metrics": "finalized_step8_metrics",
    "final-b-ranknet": "step15_production_b",
    "image-only-loio": "step13_image_only_loio",
    "image-only-ltio": "step14_image_only_l2io",
    "image-only-5fold": "image_only_score_b_5fold",
    "image-only-nested-l2": "image_only_score_b_nested_l2",
    "task-a": "task_a_production_model",
    "task-b": "task_b_production_model",
    "step9-clean-visual-lift": "step9_clean_visual_lift",
    "step10-decorrelated-visual-residual": "step10_decorrelated_visual_residual",
    "step11-repeated-stability": "repeated_step11_stability",
    "step12-identity-purged-residual": "step12_identity_purged_residual",
    "step17-retest-anchor": "step17_retest_anchor_validation",
    "step18-paired-bootstrap": "step18_paired_cluster_bootstrap",
    "step19-within-identity": "step19_within_identity_validation",
    "step20-latent-context": "step20_latent_context_holdout",
    "step21-patch-vs-cls-loio": "step21_patch_vs_cls_loio",
    "step22-certified-ranknet": "step22_certified_ranknet",
    "step23-attention-patch-loio": "step23_attention_patch_pooling",
    "step24-attention-overfit": "step24_attention_overfit_sanity",
    "step25-nested-attention": "step25_nested_attention_loio",
    "step26-frozen-encoder-bakeoff": "step26_frozen_encoder_bakeoff",
    "step27-nested-l2io": "step27_nested_l2io",
    "step28-fusion-ow": "step28_fusion_ow_nested_loio",
    "step28-purged-splits": "step28_purged_split_validation",
    "step28-strict-l2io-ow": "step28_strict_l2io_ow",
    "step29-s2ow-construct-validity": "step29_s2ow_construct_validity",
    "step30-s2ow-concept-readout": "step30_s2ow_concept_readout",
    "step30b-core5-concept-readout": "step30b_core5_concept_readout",
    "step31a-pooled-importance-anchor-panel": "step31a_pooled_importance_anchor_panel",
    "step31b-anchor-annotation-audit": "step31b_anchor_annotation_audit",
    "step32-back-view-candidate-validation": "step32_back_view_candidate_validation",
    "step32-image-anchored-probes": "step32_image_anchored_probes",
    "step36-counter-prior-qpool": "step36_counter_prior_qpool",
    "step36a-recover-linear": "step36a_recover_linear_predictions",
    "step36a-counter-prior": "step36a_counter_prior_audit",
    "step36b-counter-balanced-qpool": "step36b_counter_balanced_qpool",
    "step36c-counter-retest": "step36c_counter_retest_audit",
    "step36cr-paired-counter-headroom": "step36cr_paired_counter_headroom",
    "step37-strict-linear-cp3": "step37_strict_linear_cp3",
    "step38-siglip2-model-a": "step38_siglip2_model_a",
    "step39-production-a-s2": "step39_production_a_s2",
    "step40-siglip2-spatial-counter": "step40_siglip2_spatial_counter",
    "step40p-nested-spatial-pilot": "step40p_nested_spatial_pilot",
    "step40p-r0-inner-loio-preflight": "step40p_r0_inner_loio_preflight",
    "step40p-r1-spatial-pilot": "step40p_r1_spatial_pilot",
    "step41a-attention-lora-preflight": "step41a_attention_lora_preflight",
    "step41a-r1-attention-lora-preflight": "step41a_r1_attention_lora_preflight",
    "step41a-r2-attention-lora-preflight": "step41a_r2_attention_lora_preflight",
    "step41a-r3-residual-margin-audit": "step41a_r3_residual_margin_audit",
    "step41a-r4-loraplus-lr-range": "step41a_r4_loraplus_lr_range",
    "step41a-r4e-loraplus-lr-extension": "step41a_r4e_loraplus_lr_extension",
    "step42-head-fixed-audit": "step42_head_fixed_descriptive_audit",
    "step42b-distance-transitions": "step42b_distance_transition_audit",
    "step43a-production-preflight": "step43a_production_compatible_preflight",
    "step43b0-deterministic-manifest": "step43b0_deterministic_16fold_manifest",
    "step43b0-r1-deterministic-manifest": "step43b0_r1_deterministic_15fold_manifest",
    "step43b1-full-crossfit": "step43b1_full_15fold_crossfit",
    "step43b2-prospective-power-audit": "step43b2_prospective_power_audit",
    "step43c0-r1-reconstruct-and-freeze": "step43c0_r1_reconstruct_and_freeze",
    "step43c1-descriptive-replication": "step43c1_descriptive_replication",
    "step43c2-recover-and-artifact-gate": "step43c2_recover_and_artifact_gate",
    "step43d-l2io-head-transfer": "step43d_l2io_head_transfer",
    "step43e0-training-budget-audit": "step43e0_training_budget_audit",
    "step43e-nested-l2io": "step43e_nested_l2io",
    "step43f0-extreme-error-audit": "step43f0_extreme_error_audit",
    "step43f1-within-identity-retest": "step43f1_within_identity_retest",
    "step43g-attention-head-search": "step43g_attention_head_search",
    "step43g1-matched-w-retest": "step43g1_matched_w_retest_evaluation",
    "step43h0-disagreement-power-audit": "step43h0_disagreement_power_audit",
    "step43h0-r1-endpoint-power-audit": "step43h0_r1_endpoint_power_audit",
    "step43h1-final-refit-reserve-freeze": "step43h1_final_refit_reserve_freeze",
    "step43h1-r1-expand-reserve-freeze": "step43h1_r1_expand_reserve_freeze",
    "step43h2-reserve-campaign-construction": "step43h2_reserve_campaign_construction",
    "step43h2-r1-reserve200-preregistration": "step43h2_r1_reserve200_preregistration",
    "step43h2-r1-make-ranking-state": "step43h2_r1_make_ranking_state",
    "step43h3-prospective-analysis": "step43h3_prospective_analysis",
    "step44a-global-level-metric-audit": "step44a_global_level_metric_audit",
    "step44b-canonical-global-target": "step44b_canonical_global_target",
    "step44c-level-metric-contract": "step44c_level_metric_contract",
    "step45-trainer-contract": "step45_trainer_contract",
    "step45a-close-technical-debt": "step45a_close_technical_debt",
    "step45b-anchor-calibration": "step45b_anchor_calibration",
    "step46a-frozen-readout-comparison": "step46a_frozen_readout_comparison",
    "step46a-r1-lower-lr-resolution": "step46a_r1_lower_lr_resolution",
    "step46a-r2-report-and-inference-specs": "step46a_r2_report_and_inference_specs",
    "step46b-last-block-finetune": "step46b_last_block_finetune",
    "step46b-s1-last-block-screen": "step46b_s1_last_block_screen",
    "step46b-s1-r0-rematerialize-predecessors": "step46b_s1_r0_rematerialize_predecessors",
    "step46b-s1-r1-certify-checkpoint0": "step46b_s1_r1_certify_checkpoint0",
    "step46b-s1-acceleration-ablation": "step46b_s1_acceleration_ablation",
    "step46c-prodigy-optimizer-guard": "step46c_prodigy_optimizer_guard",
    "step47a-joint-from-start-prodigy": "step47a_joint_from_start_prodigy",
    "step47b-joint4-adamw-lr-search": "step47b_joint4_adamw_lr_search",
    "step47c-paired-seed-calibration": "step47c_paired_seed_calibration",
    "step48a-freeze-challenger-external-preflight": "step48a_freeze_challenger_external_preflight",
    "step48b-external-sampling-design-audit": "step48b_external_sampling_design_audit",
    "step48b-r1-estimand-feasibility-repair": "step48b_r1_estimand_feasibility_repair",
    "step48c-external-contract-repair": "step48c_external_contract_repair",
    "step48c-r1-paired-target-anchor-topology": "step48c_r1_paired_target_anchor_topology",
    "step48c-r2-direct-anchored-ordinal": "step48c_r2_direct_anchored_ordinal",
    "step48d-frozen-single-layer-ablation": "step48d_frozen_single_layer_ablation",
    "step48d-r1-layer-horizon-repair": "step48d_r1_layer_horizon_repair",
    "step48e-zero-label-prefreeze-audit": "step48e_zero_label_prefreeze_audit",
    "step48e-r1-manifest-fidelity-repair": "step48e_r1_manifest_fidelity_repair",
    "step48f-descriptive-arm-materialization-prediction-freeze": "step48f_descriptive_arm_materialization_prediction_freeze",
    "step48f-r1-schedulefree-eval-state-rematerialization": "step48f_r1_schedulefree_eval_state_rematerialization",
    "step49a-blinded-label-lock": "step49a_blinded_label_lock",
    "step49b-r1-blind-endpoint-amendment": "step49b_r1_blind_endpoint_amendment",
    "step49b-atomic-unblinding-analysis": "step49b_atomic_unblinding_analysis",
    "step50b-interpretation-audit-project-ledger": "step50b_interpretation_audit_project_ledger",
    "step50b-r1-semantic-ledger-inventory-repair": "step50b_r1_semantic_ledger_inventory_repair",
    "step51a-linear-factorial-training-screen": "step51a_linear_factorial_training_screen",
    "step51b-matched-explicit-regularization-bridge": "step51b_matched_explicit_regularization_bridge",
    "step52a-shared-parameter-l26-l22-fusion": "step52a_shared_parameter_l26_l22_fusion",
    "step52b-validation-resolution-direct-ordinal-audit": "step52b_validation_resolution_direct_ordinal_audit",
    "step52c-direct-ordinal-checkpoint-selection-calibration": "step52c_direct_ordinal_checkpoint_selection_calibration",
    "step53a-tune14-l26-reference-materialization": "step53a_tune14_l26_reference_materialization",
    "step53b-corrected-l26-l22-fusion-tune14": "step53b_corrected_l26_l22_fusion_tune14",
    "step53b-r1-direct-ordinal-coverage-scale-repair": "step53b_r1_direct_ordinal_coverage_scale_repair",
    "step53b-r2-concordance-fusion-offset-guard": "step53b_r2_concordance_fusion_offset_guard",
    "step53b-r3-direct-ordinal-layer-surfaces": "step53b_r3_direct_ordinal_layer_surfaces",
    "step54a-pe-l25-tune14": "step54a_pe_l25_tune14",
    "step54b-direct-ordinal-recipe-replay": "step54b_direct_ordinal_recipe_replay",
    "step55a-pooled-branch-ablation": "step55a_pooled_branch_ablation",
    "step55a-r1-historical-scope-frontier-audit": "step55a_r1_historical_scope_frontier_audit",
    "step55b-p-nonzero-attention-initialization-preflight": "step55b_p_nonzero_attention_initialization_preflight",
    "step55b-joint4-nonzero-initialization-ablation": "step55b_joint4_nonzero_initialization_ablation",
    "step55c-p-loss-normalization-equivalence-preflight": "step55c_p_loss_normalization_equivalence_preflight",
    "step55c-group-weight-vs-mean-pair": "step55c_group_weight_vs_mean_pair",
    "step55d-p-unit-mass-mean-pair-preflight": "step55d_p_unit_mass_mean_pair_preflight",
    "step55d-mean-pair-scale-reweighting-decomposition": "step55d_mean_pair_scale_reweighting_decomposition",
    "step55e-p-l25-penultimate-finetune-preflight": "step55e_p_l25_penultimate_finetune_preflight",
    "step55e-l25-producer-block-finetune": "step55e_l25_producer_block_finetune",
    "step55e-r1-full-population-cache-provenance": "step55e_r1_full_population_cache_provenance",
    "step56a-full-resolution-layer-screen": "step56a_full_resolution_layer_screen",
    "step56b-joint4-branch-decomposition-score-mixing": "step56b_joint4_branch_decomposition_score_mixing",
    "step56c-scale-calibrated-branch-mixing": "step56c_scale_calibrated_branch_mixing",
    "step56c-r1-exact-token-branch-mixing": "step56c_r1_exact_token_branch_mixing",
    "step57a-zero-pooled-linear-initialization": "step57a_zero_pooled_linear_initialization",
    "step57b-training-only-theta-gradient-cap": "step57b_training_only_theta_gradient_cap",
    "step58a-counter-prior-response-audit": "step58a_counter_prior_response_audit",
    "step58b-transductive-lookup-reference": "step58b_transductive_lookup_reference",
    "step59a-full-data-l26-gw-horizon-transfer": "step59a_full_data_l26_gw_horizon_transfer",
    "step59b-full-data-counter-prior-transfer-audit": "step59b_full_data_counter_prior_transfer_audit",
    "step60a-matched-image-heldout-horizon-transfer": "step60a_matched_image_heldout_horizon_transfer",
    "step60b-target-heldout-seen-anchor-endpoint-certification": "step60b_target_heldout_seen_anchor_endpoint_certification",
    "step61a-full-l10-l25-block-skip-scan": "step61a_full_l10_l25_block_skip_scan",
    "step43a-r1-group-oof-production-head": "step43a_r1_group_oof_production_head",
    "explore-prodigy-head": "explore_prodigy_head",
    "step31c-targeted-anchor-panel": "step31c_targeted_anchor_panel",
    "step31-marginal-concepts-name-transfer": "step31_marginal_concepts_name_transfer",
}


def main() -> None:
    if len(sys.argv) >= 2 and sys.argv[1] in COMMAND_MODULES:
        command = sys.argv[1]
        module = importlib.import_module(COMMAND_MODULES[command])
        command_args = list(sys.argv[2:])
        sys.argv = [f"{sys.argv[0]} {command}", *command_args]
        module.main()
        return

    parser = argparse.ArgumentParser(description="Unified CLI for the ranking project.")
    parser.add_argument("command", choices=sorted(COMMAND_MODULES))
    parser.parse_args()
